### ISSUE TITLE
TODO checklist

### ISSUE THREAD

**Issue by jonathancallahan** [pnwairfire/monitoring-databrowser-v5#1]
Items as they come up:

-----
_TODO:_

**mv5-real-time**

_New in 2026_

- [ ] Add ability to search for locations. (6/8/2026)

_New in 2025_

- [ ] It would be fun to be able to rename monitors/sensors for the duration of a session (6/27/2025)

_New in 2024_

- [ ] add GFS winds a la Windy (see Stuart) (3/15/24)
- [ ] plan for multi-pollutant (CO, O3, PM10) (3/15/24)
- [ ] Katy from ARA training wants instrument type in Mv5 metadata (6/26/24)

**rea-time-co**
- [ ] load v3 CO data and meta (12/11/24)
- [ ] create layer from CO meta (12/11/24)
- [ ] reduce number of plots (12/11/24)
- [ ] my_ functions to replace air-monitor-plots version. (12/11/24)

_New in 2023_
- [ ] Joel would like to see connected zoom. (Use separate `current_x_zoom` in gui_state.) (6/12/23)
- [ ] CSV file generation doesn't always return all files. (7/27/23)
https://airfire-monitoring-guis.s3.us-west-2.amazonaws.com/ara/v5/real-time/index.html?centerlat=36.5979&centerlon=-110.6982&zoom=6&monitors=ae18f23c92c781a5_wrcc.sm23,b0e3282eff130677_840MMEKD0001,b9b5b4b14a948ae0_usfs.1054,bba742d65e24fcf3_usfs.1035,877cded2c57aec49_usfs.1076,6a9d812dd5f11126_usfs.1075,905003e2a2d6e260_usfs.1074
- [ ] Put monitors with high readings on top. (7/27/23)
- [ ] Have a way to display AQI values rather than ug/m3. (8/23/23)

----
_Items finished by 2025-09-16_

**production and dev**

- [x] Include a CONFIG file just like we have for FASM. (5/21/25)
- [x] place download data service/link in password protected area (3/15/24)
- [x] ~add a no-hms option to skip satellite detects entirely~ toggle layers instead (7/26/24)
- [x] ~use Stuart's exclusion list~ using CONFIG instead

----
_Items finished by 2025-09-10_

**dev version**

- [x] use local time axis in all plots (currently UTC except for diurnal plot) (5/30/25)
- [x] PurpleAir monitors in URL aren't pre-selected when page renders (7/15/24)
- [x] add control to show/hide different layers (8/2/24)

----
_Items finished by 2024-07-23_

- [x] add smoke plumes (FASM feed) (3/15/24)
- [x] add fires (FASM feed) (3/15/24)
- [x] **Improve performance by putting (fire) points on a single Canvas layer:** https://stackoverflow.com/questions/43015854/large-dataset-of-markers-or-dots-in-leaflet
- [x] swap order of things under popups to show most universal first: latency, latest nowcast, latest pm2.5, yesterday pm2.5, AQSID, elevation (3/15/24)
- [x] change wording for "Unmonitored Location" to "(Mouse Over)" or similar (3/15/24)
- [x] updated to use PM2.5_2024 NAAQS (3/15/24)

----
_Items finished by 2023-08-23_

- [x] Hourly bar plots show purple bars in the "red" zone. Is this an issue with air-monitor-plots? (7/27)
- [x] Use Stuart's basemap from FASM v3. (7/27)
- [x] Add sensor IDs to URL and initialize UI using sensor IDs in URL. (7/27)

----
_Items finished by 2023-07-27_

- [x] sensor_data_store.js .(1/23)
- [x] Display PA data with separate callback to: 1) load data from Stuart's files; 2) plot data (1/23)

----
_Items finished by 2023-01-23_

- [x] Initial checkin of `mv5-simple` minimum viable product.
